SQL> alter user system grant connect through donghua;

User altered.

[(orcl)oracle@oracle19c ~]$ sql donghua[system]/donghua_password@orclpdb

SQLcl: Release 19.1 Production on Thu Nov 21 04:23:50 2019

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.5.0.0.0

SQL> show user;
USER is "SYSTEM"

SQL> show connection
CONNECTION:
 DONGHUA@jdbc:oracle:oci8:@orclpdb 
CONNECTION_IDENTIFIER:
 orclpdb
CONNECTION_DB_VERSION:
 Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
 Version 19.5.0.0.0
NOLOG:
 false
PRELIMAUTH:
 false
SQL> show con_id
CON_ID 
------------------------------
3
SQL> show jdbc
-- Database Info --
Database Product Name: Oracle
Database Product Version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.5.0.0.0
Database Major Version: 19
Database Minor Version: 5
-- Driver Info --
Driver Name: Oracle JDBC driver
Driver Version: 19.3.0.0.0
Driver Major Version: 19
Driver Minor Version: 3
Driver URL: jdbc:oracle:oci8:@orclpdb
Driver Location: 
resource: oracle/jdbc/OracleDriver.class
jar: /u01/db/jdbc/lib/ojdbc8.jar  
JarSize: 4219374  
JarDate: Sun Nov 10 12:44:43 SGT 2019  
resourceSize: 2604  
resourceDate: Thu Apr 04 20:38:40 SGT 2019


SQL> select sys_context('userenv','sid') from dual;

SYS_CONTEXT('USERENV','SID')                                                    
--------------------------------------------------------------------------------
183                                                                             

SQL> select userenv('sid') from dual;

USERENV('SID')
--------------
           183

SQL> show user;
USER is "SYSTEM"

SQL> set sqlformat xml

SQL> select * from v$session where sid=183;
<?xml version='1.0'  encoding='UTF-8' ?>
<RESULTS>
	<ROW>
		<COLUMN NAME="SADDR"><![CDATA[00000000AB8B4318]]></COLUMN>
		<COLUMN NAME="SID"><![CDATA[183]]></COLUMN>
		<COLUMN NAME="SERIAL#"><![CDATA[24283]]></COLUMN>
		<COLUMN NAME="AUDSID"><![CDATA[440073]]></COLUMN>
		<COLUMN NAME="PADDR"><![CDATA[00000000AB576AA0]]></COLUMN>
		<COLUMN NAME="USER#"><![CDATA[9]]></COLUMN>
		<COLUMN NAME="USERNAME"><![CDATA[SYSTEM]]></COLUMN>
		<COLUMN NAME="COMMAND"><![CDATA[3]]></COLUMN>
		<COLUMN NAME="OWNERID"><![CDATA[2147483644]]></COLUMN>
		<COLUMN NAME="TADDR"><![CDATA[]]></COLUMN>
		<COLUMN NAME="LOCKWAIT"><![CDATA[]]></COLUMN>
		<COLUMN NAME="STATUS"><![CDATA[ACTIVE]]></COLUMN>
		<COLUMN NAME="SERVER"><![CDATA[DEDICATED]]></COLUMN>
		<COLUMN NAME="SCHEMA#"><![CDATA[9]]></COLUMN>
		<COLUMN NAME="SCHEMANAME"><![CDATA[SYSTEM]]></COLUMN>
		<COLUMN NAME="OSUSER"><![CDATA[oracle]]></COLUMN>
		<COLUMN NAME="PROCESS"><![CDATA[26824]]></COLUMN>
		<COLUMN NAME="MACHINE"><![CDATA[oracle19c]]></COLUMN>
		<COLUMN NAME="PORT"><![CDATA[24386]]></COLUMN>
		<COLUMN NAME="TERMINAL"><![CDATA[pts/0]]></COLUMN>
		<COLUMN NAME="PROGRAM"><![CDATA[java@oracle19c (TNS V1-V3)]]></COLUMN>
		<COLUMN NAME="TYPE"><![CDATA[USER]]></COLUMN>
		<COLUMN NAME="SQL_ADDRESS"><![CDATA[0000000084225508]]></COLUMN>
		<COLUMN NAME="SQL_HASH_VALUE"><![CDATA[3728947566]]></COLUMN>
		<COLUMN NAME="SQL_ID"><![CDATA[9unzbtgg46fbf]]></COLUMN>
		<COLUMN NAME="SQL_CHILD_NUMBER"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="SQL_EXEC_START"><![CDATA[21-NOV-19]]></COLUMN>
		<COLUMN NAME="SQL_EXEC_ID"><![CDATA[16777217]]></COLUMN>
		<COLUMN NAME="PREV_SQL_ADDR"><![CDATA[0000000092B37A10]]></COLUMN>
		<COLUMN NAME="PREV_HASH_VALUE"><![CDATA[302297662]]></COLUMN>
		<COLUMN NAME="PREV_SQL_ID"><![CDATA[2jnz9d8909cjy]]></COLUMN>
		<COLUMN NAME="PREV_CHILD_NUMBER"><![CDATA[2]]></COLUMN>
		<COLUMN NAME="PREV_EXEC_START"><![CDATA[21-NOV-19]]></COLUMN>
		<COLUMN NAME="PREV_EXEC_ID"><![CDATA[16777218]]></COLUMN>
		<COLUMN NAME="PLSQL_ENTRY_OBJECT_ID"><![CDATA[]]></COLUMN>
		<COLUMN NAME="PLSQL_ENTRY_SUBPROGRAM_ID"><![CDATA[]]></COLUMN>
		<COLUMN NAME="PLSQL_OBJECT_ID"><![CDATA[]]></COLUMN>
		<COLUMN NAME="PLSQL_SUBPROGRAM_ID"><![CDATA[]]></COLUMN>
		<COLUMN NAME="MODULE"><![CDATA[java@oracle19c (TNS V1-V3)]]></COLUMN>
		<COLUMN NAME="MODULE_HASH"><![CDATA[780768561]]></COLUMN>
		<COLUMN NAME="ACTION"><![CDATA[]]></COLUMN>
		<COLUMN NAME="ACTION_HASH"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="CLIENT_INFO"><![CDATA[]]></COLUMN>
		<COLUMN NAME="FIXED_TABLE_SEQUENCE"><![CDATA[117870]]></COLUMN>
		<COLUMN NAME="ROW_WAIT_OBJ#"><![CDATA[446]]></COLUMN>
		<COLUMN NAME="ROW_WAIT_FILE#"><![CDATA[9]]></COLUMN>
		<COLUMN NAME="ROW_WAIT_BLOCK#"><![CDATA[1433]]></COLUMN>
		<COLUMN NAME="ROW_WAIT_ROW#"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="TOP_LEVEL_CALL#"><![CDATA[94]]></COLUMN>
		<COLUMN NAME="LOGON_TIME"><![CDATA[21-NOV-19]]></COLUMN>
		<COLUMN NAME="LAST_CALL_ET"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="PDML_ENABLED"><![CDATA[NO]]></COLUMN>
		<COLUMN NAME="FAILOVER_TYPE"><![CDATA[NONE]]></COLUMN>
		<COLUMN NAME="FAILOVER_METHOD"><![CDATA[NONE]]></COLUMN>
		<COLUMN NAME="FAILED_OVER"><![CDATA[NO]]></COLUMN>
		<COLUMN NAME="RESOURCE_CONSUMER_GROUP"><![CDATA[SYS_GROUP]]></COLUMN>
		<COLUMN NAME="PDML_STATUS"><![CDATA[DISABLED]]></COLUMN>
		<COLUMN NAME="PDDL_STATUS"><![CDATA[ENABLED]]></COLUMN>
		<COLUMN NAME="PQ_STATUS"><![CDATA[ENABLED]]></COLUMN>
		<COLUMN NAME="CURRENT_QUEUE_DURATION"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="CLIENT_IDENTIFIER"><![CDATA[]]></COLUMN>
		<COLUMN NAME="BLOCKING_SESSION_STATUS"><![CDATA[NOT IN WAIT]]></COLUMN>
		<COLUMN NAME="BLOCKING_INSTANCE"><![CDATA[]]></COLUMN>
		<COLUMN NAME="BLOCKING_SESSION"><![CDATA[]]></COLUMN>
		<COLUMN NAME="FINAL_BLOCKING_SESSION_STATUS"><![CDATA[NOT IN WAIT]]></COLUMN>
		<COLUMN NAME="FINAL_BLOCKING_INSTANCE"><![CDATA[]]></COLUMN>
		<COLUMN NAME="FINAL_BLOCKING_SESSION"><![CDATA[]]></COLUMN>
		<COLUMN NAME="SEQ#"><![CDATA[163]]></COLUMN>
		<COLUMN NAME="EVENT#"><![CDATA[443]]></COLUMN>
		<COLUMN NAME="EVENT"><![CDATA[SQL*Net more data to client]]></COLUMN>
		<COLUMN NAME="P1TEXT"><![CDATA[driver id]]></COLUMN>
		<COLUMN NAME="P1"><![CDATA[1413697536]]></COLUMN>
		<COLUMN NAME="P1RAW"><![CDATA[0000000054435000]]></COLUMN>
		<COLUMN NAME="P2TEXT"><![CDATA[#bytes]]></COLUMN>
		<COLUMN NAME="P2"><![CDATA[8103]]></COLUMN>
		<COLUMN NAME="P2RAW"><![CDATA[0000000000001FA7]]></COLUMN>
		<COLUMN NAME="P3TEXT"><![CDATA[]]></COLUMN>
		<COLUMN NAME="P3"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="P3RAW"><![CDATA[00]]></COLUMN>
		<COLUMN NAME="WAIT_CLASS_ID"><![CDATA[2000153315]]></COLUMN>
		<COLUMN NAME="WAIT_CLASS#"><![CDATA[7]]></COLUMN>
		<COLUMN NAME="WAIT_CLASS"><![CDATA[Network]]></COLUMN>
		<COLUMN NAME="WAIT_TIME"><![CDATA[-1]]></COLUMN>
		<COLUMN NAME="SECONDS_IN_WAIT"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="STATE"><![CDATA[WAITED SHORT TIME]]></COLUMN>
		<COLUMN NAME="WAIT_TIME_MICRO"><![CDATA[28]]></COLUMN>
		<COLUMN NAME="TIME_REMAINING_MICRO"><![CDATA[]]></COLUMN>
		<COLUMN NAME="TIME_SINCE_LAST_WAIT_MICRO"><![CDATA[21]]></COLUMN>
		<COLUMN NAME="SERVICE_NAME"><![CDATA[orclpdb]]></COLUMN>
		<COLUMN NAME="SQL_TRACE"><![CDATA[DISABLED]]></COLUMN>
		<COLUMN NAME="SQL_TRACE_WAITS"><![CDATA[FALSE]]></COLUMN>
		<COLUMN NAME="SQL_TRACE_BINDS"><![CDATA[FALSE]]></COLUMN>
		<COLUMN NAME="SQL_TRACE_PLAN_STATS"><![CDATA[FIRST EXEC]]></COLUMN>
		<COLUMN NAME="SESSION_EDITION_ID"><![CDATA[134]]></COLUMN>
		<COLUMN NAME="CREATOR_ADDR"><![CDATA[00000000AB576AA0]]></COLUMN>
		<COLUMN NAME="CREATOR_SERIAL#"><![CDATA[36]]></COLUMN>
		<COLUMN NAME="ECID"><![CDATA[]]></COLUMN>
		<COLUMN NAME="SQL_TRANSLATION_PROFILE_ID"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="PGA_TUNABLE_MEM"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="SHARD_DDL_STATUS"><![CDATA[DISABLED]]></COLUMN>
		<COLUMN NAME="CON_ID"><![CDATA[3]]></COLUMN>
		<COLUMN NAME="EXTERNAL_NAME"><![CDATA[]]></COLUMN>
		<COLUMN NAME="PLSQL_DEBUGGER_CONNECTED"><![CDATA[FALSE]]></COLUMN>
	</ROW>
</RESULTS>


QL> select * from dba_proxies;
<?xml version='1.0'  encoding='UTF-8' ?>
<RESULTS>
	<ROW>
		<COLUMN NAME="PROXY"><![CDATA[DONGHUA]]></COLUMN>
		<COLUMN NAME="CLIENT"><![CDATA[SYSTEM]]></COLUMN>
		<COLUMN NAME="AUTHENTICATION"><![CDATA[NO]]></COLUMN>
		<COLUMN NAME="AUTHORIZATION_CONSTRAINT"><![CDATA[PROXY MAY ACTIVATE ALL CLIENT ROLES]]></COLUMN>
		<COLUMN NAME="ROLE"><![CDATA[]]></COLUMN>
		<COLUMN NAME="PROXY_AUTHORITY"><![CDATA[DATABASE]]></COLUMN>
	</ROW>
</RESULTS>

SQL> select * from proxy_users;
<?xml version='1.0'  encoding='UTF-8' ?>
<RESULTS>
	<ROW>
		<COLUMN NAME="PROXY"><![CDATA[DONGHUA]]></COLUMN>
		<COLUMN NAME="CLIENT"><![CDATA[SYSTEM]]></COLUMN>
		<COLUMN NAME="AUTHENTICATION"><![CDATA[NO]]></COLUMN>
		<COLUMN NAME="FLAGS"><![CDATA[PROXY MAY ACTIVATE ALL CLIENT ROLES]]></COLUMN>
	</ROW>
</RESULTS>


SQL> select * from v$session_connect_info where sid=183;
<?xml version='1.0'  encoding='UTF-8' ?>
<RESULTS>
	<ROW>
		<COLUMN NAME="SID"><![CDATA[183]]></COLUMN>
		<COLUMN NAME="SERIAL#"><![CDATA[24283]]></COLUMN>
		<COLUMN NAME="AUTHENTICATION_TYPE"><![CDATA[PROXY]]></COLUMN>
		<COLUMN NAME="OSUSER"><![CDATA[oracle]]></COLUMN>
		<COLUMN NAME="NETWORK_SERVICE_BANNER"><![CDATA[TCP/IP NT Protocol Adapter for Linux: Version 19.0.0.0.0 - Production]]></COLUMN>
		<COLUMN NAME="CLIENT_CHARSET"><![CDATA[UTF8]]></COLUMN>
		<COLUMN NAME="CLIENT_CONNECTION"><![CDATA[Homogeneous]]></COLUMN>
		<COLUMN NAME="CLIENT_OCI_LIBRARY"><![CDATA[Home-based]]></COLUMN>
		<COLUMN NAME="CLIENT_VERSION"><![CDATA[19.5.0.0.0]]></COLUMN>
		<COLUMN NAME="CLIENT_DRIVER"><![CDATA[jdbcoci : 19.3.0.0.0]]></COLUMN>
		<COLUMN NAME="CLIENT_LOBATTR"><![CDATA[Client Temp Lob Rfc On]]></COLUMN>
		<COLUMN NAME="CLIENT_REGID"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="CON_ID"><![CDATA[3]]></COLUMN>
	</ROW>
	<ROW>
		<COLUMN NAME="SID"><![CDATA[183]]></COLUMN>
		<COLUMN NAME="SERIAL#"><![CDATA[24283]]></COLUMN>
		<COLUMN NAME="AUTHENTICATION_TYPE"><![CDATA[PROXY]]></COLUMN>
		<COLUMN NAME="OSUSER"><![CDATA[oracle]]></COLUMN>
		<COLUMN NAME="NETWORK_SERVICE_BANNER"><![CDATA[Encryption service for Linux: Version 19.0.0.0.0 - Production]]></COLUMN>
		<COLUMN NAME="CLIENT_CHARSET"><![CDATA[UTF8]]></COLUMN>
		<COLUMN NAME="CLIENT_CONNECTION"><![CDATA[Homogeneous]]></COLUMN>
		<COLUMN NAME="CLIENT_OCI_LIBRARY"><![CDATA[Home-based]]></COLUMN>
		<COLUMN NAME="CLIENT_VERSION"><![CDATA[19.5.0.0.0]]></COLUMN>
		<COLUMN NAME="CLIENT_DRIVER"><![CDATA[jdbcoci : 19.3.0.0.0]]></COLUMN>
		<COLUMN NAME="CLIENT_LOBATTR"><![CDATA[Client Temp Lob Rfc On]]></COLUMN>
		<COLUMN NAME="CLIENT_REGID"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="CON_ID"><![CDATA[3]]></COLUMN>
	</ROW>
	<ROW>
		<COLUMN NAME="SID"><![CDATA[183]]></COLUMN>
		<COLUMN NAME="SERIAL#"><![CDATA[24283]]></COLUMN>
		<COLUMN NAME="AUTHENTICATION_TYPE"><![CDATA[PROXY]]></COLUMN>
		<COLUMN NAME="OSUSER"><![CDATA[oracle]]></COLUMN>
		<COLUMN NAME="NETWORK_SERVICE_BANNER"><![CDATA[Crypto-checksumming service for Linux: Version 19.0.0.0.0 - Production]]></COLUMN>
		<COLUMN NAME="CLIENT_CHARSET"><![CDATA[UTF8]]></COLUMN>
		<COLUMN NAME="CLIENT_CONNECTION"><![CDATA[Homogeneous]]></COLUMN>
		<COLUMN NAME="CLIENT_OCI_LIBRARY"><![CDATA[Home-based]]></COLUMN>
		<COLUMN NAME="CLIENT_VERSION"><![CDATA[19.5.0.0.0]]></COLUMN>
		<COLUMN NAME="CLIENT_DRIVER"><![CDATA[jdbcoci : 19.3.0.0.0]]></COLUMN>
		<COLUMN NAME="CLIENT_LOBATTR"><![CDATA[Client Temp Lob Rfc On]]></COLUMN>
		<COLUMN NAME="CLIENT_REGID"><![CDATA[0]]></COLUMN>
		<COLUMN NAME="CON_ID"><![CDATA[3]]></COLUMN>
	</ROW>
</RESULTS>
SQL> 

SQL> alter user system grant connect through donghua authenticated using password;

User altered.
SQL> conn donghua[system]@orclpdb
Password? (**********?) ********
ERROR:
ORA-28150: proxy not authorized to connect as client

# No issue for connection in SQL Developer with proxy user and proxy PASSWORD
